name: The site with no name!
title: Sinan Aumarah
description: Sinan Aumarah Portfolio
url: https://sinan-aumarah.github.io/
locale: en_US
email: sinan.wrk@gmail.com

about:
  job_title: Senior Software Consultant
  website_domain: sinan-aumarah.github.io
  website_url: https://sinan-aumarah.github.io/


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed


# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - github-pages

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, .sass-cache, .DS_Store]
